Document: indicator-ip
Title: Debian indicator-ip Manual
Author: <insert document author here>
Abstract: This manual describes what indicator-ip is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/indicator-ip/indicator-ip.sgml.gz

Format: postscript
Files: /usr/share/doc/indicator-ip/indicator-ip.ps.gz

Format: text
Files: /usr/share/doc/indicator-ip/indicator-ip.text.gz

Format: HTML
Index: /usr/share/doc/indicator-ip/html/index.html
Files: /usr/share/doc/indicator-ip/html/*.html
